name       : qt6-connectivity
version    : 6.3.0
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtconnectivity-everywhere-src-6.3.0.tar.xz : 98f7132e3aa56db2be4800897a0514248a7ae83791b69f8162d628e187b0e61a
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Connectivity components
description: |
    Qt connectivity provides access to Bluetooth hardware.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(bluez)
rundeps    :
    - devel :
        - bluez-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
