name       : qt6-connectivity
version    : 6.2.2
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtconnectivity-everywhere-src-6.2.2.tar.xz : bb6e916d029a7a00cedea161fa95e53e6f060a8415e82cc350e846b39a3d5cec
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Connectivity components
description: |
    Qt connectivity provides access to Bluetooth hardware.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(bluez)
rundeps    :
    - devel :
        - bluez-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
